DAT-12406. upgraded test-harness version to 1.0.8. added LiquibaseHarnessFoundationalCompatibilitySuite
liquibase/liquibase-yugabytedb pull request #58
Opened 2022-11-16 16:11 UTC by PavloTytarchuk

2022-11-17 14:49 UTC, KushnirykOleh requested changes

2022-11-17 14:49 UTC, KushnirykOleh commented on pom.xml
> +            <!-- This syntax means open-ended version range. Take newest accessible starting from 4.14.0 -->
remove this comment, it doesn't make sense here. Extension doesn't use newest available version, but specific one

2022-11-17 14:49 UTC, KushnirykOleh commented on src/test/resources/liquibase/harness/change/changelogs/yugabytedb/addAutoIncrement.xml
> +<?xml version="1.0" encoding="UTF-8"?>
i don't think we need to override all these changelog files, only those that are different for this platform.
Same for expectedSnapshot. If default works, let's use it.
Only expectedSQL need to used for every platform separately

2022-11-18 11:05 UTC, PavloTytarchuk commented on pom.xml
> +            <!-- This syntax means open-ended version range. Take newest accessible starting from 4.14.0 -->
removed.

2022-11-18 11:06 UTC, PavloTytarchuk commented on src/test/resources/liquibase/harness/change/changelogs/yugabytedb/addAutoIncrement.xml
> +<?xml version="1.0" encoding="UTF-8"?>
removed all redundant changelolgs, Only platform specific are present now.

2022-11-18 11:39 UTC, KushnirykOleh commented on pom.xml
> +            <groupId>org.json</groupId>
not sure if we need this dependency

2022-11-18 11:40 UTC, KushnirykOleh requested changes
overall looks good, the only thing i'm not sure about is json dependency

2022-11-18 11:46 UTC, PavloTytarchuk commented on pom.xml
> +            <groupId>org.json</groupId>
removed

2022-11-18 11:47 UTC, KushnirykOleh approved these changes

2022-11-18 11:48 UTC, merged